version: "3.9"

services:
  products:
    container_name: products_projeto
    image: products
    build: .
    ports:
      - 3333:3333
    depends_on:
      - db
    environment:
      - DB_USER=daniel
      - DB_HOST=db
      - DB=defaultdb
      - DB_PASSWORD=dan199407
      - DB_PORT=5432
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5555:5432
    environment:
      - POSTGRES_USER=daniel
      - POSTGRES_PASSWORD=dan199407
      - POSTGRES_DB=defaultdb
